### ISSUE TITLE
Swagger folder missing

### ISSUE THREAD

**Issue by gzepeda** [Azure-Samples/app-service-api-dotnet-contact-list#10]
Not sure if this is an issue or not, but the swagger folder is missing from the API project. 

When you try to navigate to the URL http://localhost:51864/swagger/

You get the following error:
HTTP Error 404.0 - Not Found

**Comment by tdykstra** [comment]
There's no swagger folder; swagger output is generated by Swashbuckle.  For a more current sample, see the tutorial https://azure.microsoft.com/en-us/documentation/articles/app-service-api-dotnet-get-started/

**Comment by gzepeda** [comment]
Thanks for the reply. The line that needs to be uncommented is actually commented on SwaggerConfig.cs. Shouldn't it be uncommented by default on this sample project?

`
                            })
                        .EnableSwaggerUi(c =>
                            {
`

**Comment by tdykstra** [comment]
It's commented by default when you create an app using the API App template in Visual Studio.  It was left that way here because the sample app was used with a tutorial and the tutorial showed how to enable the Swagger UI.  In general the thinking is that it's better to have it off by default so people who aren't familiar with it don't accidentally leave the Swagger UI open on their API.

**Comment by gzepeda** [comment]
Understood. Thanks a lot for the quick reply.
